### PR TITLE
🐛 fix: no access level indicator for fileprivate members (fix #44)

### LINKED ISSUE #44: No access level indicator for fileprivate members
Members do not show an access level indicator if they have `fileprivate` access level

```swift
class aClass {
    var computedProperty: String {}
    func aFunction() {}
}

fileprivate extension aClass {
    var extComputedProperty: String { "" }
    func extFunction()
}
```

Current (unexpected) output

```
@startuml
' STYLE START
hide empty members
skinparam shadowing false
' STYLE END


class "aClass" as aClass << (C, DarkSeaGreen) >> { 
  ~computedProperty : String
  ~aFunction() 
}
class "aClass" as aClass0 << (X, Orchid) extension >> { 
  extComputedProperty : String
  extFunction() 
}

aClass <.. aClass0 : ext
@enduml
```

Expected output

```
@startuml
' STYLE START
hide empty members
skinparam shadowing false
' STYLE END


class "aClass" as aClass << (C, DarkSeaGreen) >> { 
  ~computedProperty : String
  ~aFunction() 
}
class "aClass" as aClass0 << (X, Orchid) extension >> { 
  -extComputedProperty : String
  -extFunction() 
}

aClass <.. aClass0 : ext
@enduml
```

### PR DESCRIPTION
**Pull request by MarcoEidinger**

### CODE REVIEW

**Comment by safecan** [comment]
Thank you for creating this extension! 

I recently downloaded it via homebrew and I still get no fileprivate attributes/members 😭

**Comment by MarcoEidinger** [comment]
@safecan: you need to specify `fileprivate` for `showMembersWithAccessLevel` in your `.swiftplantuml.yml` configuration file

```yml
elements:
  showMembersWithAccessLevel:
  - public
  - internal
  - private
  - fileprivate
```

**Comment by safecan** [comment]
Oh I see, and can this option be achieved within the Xcode extension preferences menu? Thanks again!

**Comment by MarcoEidinger** [comment]
> can this option be achieved within the Xcode extension preferences menu?

No.

@safecan will it help you if I include this option in the new Xcode extension version?

**Comment by safecan** [comment]
> > can this option be achieved within the Xcode extension preferences menu?
> 
> No.
> 
> @safecan will it help you if I include this option in the new Xcode extension version?

Yes <3

**Pull request merged**
